# Backend Dockerfile
# Use an official Node.js runtime as the base image
FROM 

# Set the working directory
WORKDIR


# Copy in the application code
COPY 

# Install the dependencies
RUN 

# Expose the application port
EXPOSE 

# Command and parameters to start the API
CMD ["", ""]
